scalar Date

type User {
  email: String!
  firstName: String!
  lastName: String!
  secondName: String!
  birthday: String 
  wphone: String
  phone: String
  dept: String 
  head: String 
  imageURL: String
}
type UserContact {
  label: String
  type: String!
  value: String!
}
type Query {
  me: User
}

# texx
type TexxPost {
  DocumentId:	ID!	  
  Title:	String!
  Link:		String!
  PublishedAt:	String!
  PreviewImage: String!
  PostText:	String!
}

extend type Query {
  texxPosts: [TexxPost!]!
}















