package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"errors"
	"fmt"
	"konsin1988/rt-app/auth/jwt"
	"konsin1988/rt-app/db/models"
	_ "konsin1988/rt-app/db/user"
	"konsin1988/rt-app/domain/texx"
	"konsin1988/rt-app/graph/model"
	"konsin1988/rt-app/helpers"
	"strings"
	"time"
)

// MainUser is the resolver for the mainUser field.
func (r *queryResolver) MainUser(ctx context.Context) (*model.User, error) {
	user := ctx.Value(jwt.AuthUserContextKey)
	if user == nil {
		return nil, errors.New("Unauthorized from resolver")
	}

	authUser, ok := user.(*jwt.User)
	if !ok {
		return nil, errors.New("Invalid user in context")
	}

	mainUser, err := r.UserService.AuthUser(ctx, authUser.Email)
	if err != nil {
		return nil, err
	}
	return helpers.UserToGraphModel(mainUser), nil
}

// UserByID is the resolver for the userById field.
func (r *queryResolver) UserByID(ctx context.Context, userID int32) (*model.User, error) {
	user, err := r.UserService.UserById(ctx, int(userID))
	if err != nil {
		return nil, err
	}
	return helpers.UserToGraphModel(user), nil
}

// TexxPosts is the resolver for the texxPosts field.
func (r *queryResolver) TexxPosts(ctx context.Context) ([]*model.TexxPost, error) {
	texxPosts, err := texx.FetchTexxPosts()
	if err != nil {
		return nil, err
	}

	var posts []*model.TexxPost
	for _, tex := range texxPosts {
		var bPostText strings.Builder
		for _, ContentPart := range tex.Content {
			if ContentPart.ContentType == "paragraph" {
				var bContentPartText strings.Builder
				for _, ChildrenPart := range ContentPart.ContentChildren {
					if ChildrenPart.ChildrenType == "text" {
						bContentPartText.WriteString(ChildrenPart.ChildrenText)
					} else if ChildrenPart.ChildrenType == "link" {
						bContentPartText.WriteString(ChildrenPart.LinkChildren[0].LinkText)
					}
				}
				ContentPartText := bContentPartText.String()
				bPostText.WriteString(ContentPartText)
				bPostText.WriteString("\n")
			}
		}
		PostText := bPostText.String()
		PostText = strings.Join(strings.Split(PostText, "\n")[:3], "\n\n")
		posts = append(posts, &model.TexxPost{
			DocumentID:   tex.DocumentId,
			Title:        tex.Title,
			Link:         fmt.Sprintf("https://texx.digital/news-and-articles/article/%s", tex.Slug),
			PublishedAt:  helpers.GetRussianDate(tex.PublishedAt),
			PreviewImage: fmt.Sprintf("https://texx.digital%s", tex.PreviewImage.Formats.Small.Url),
			PostText:     PostText,
		})
	}
	return posts, nil
}

// ConversationList is the resolver for the ConversationList field.
func (r *queryResolver) ConversationList(ctx context.Context) ([]*model.ConversationListItem, error) {
	user, ok := ctx.Value(jwt.MainUserContextKey).(*models.MainUser)
	if !ok {
		return nil, errors.New("Cannot load user from context")
	}

	c, err := r.AiService.GetConversationsList(ctx, user.ID)
	if err != nil {
		return nil, errors.New("Cannot load conversation list")
	}
	conversResult := make([]*model.ConversationListItem, 0)
	for _, v := range c {
		listItem := model.ConversationListItem{
			int32(v.ID),
			v.Title,
			v.CreatedAt.Format(time.RFC3339),
			v.UpdatedAt.Format(time.RFC3339),
		}
		conversResult = append(conversResult, &listItem)
	}
	return conversResult, nil
}

// ConversationByID is the resolver for the ConversationById field.
func (r *queryResolver) ConversationByID(ctx context.Context, id int32) (*model.Conversation, error) {
	c, err := r.AiService.GetConversationById(ctx, int(id))
	if err != nil {
		return nil, errors.New("Cannot get conversation by id")
	}
	messages := make([]*model.Message, 0)
	for _, i := range c.Messages {
		m := model.Message{
			ID:        int32(i.ID),
			Role:      model.MessageRole(i.Role),
			Content:   i.Content,
			CreatedAt: helpers.FormatRussian(i.CreatedAt),
		}
		messages = append(messages, &m)
	}
	conversation := model.Conversation{
		ID:        int32(c.ID),
		Title:     &c.Title,
		Messages:  messages,
		CreatedAt: c.CreatedAt.Format(time.RFC3339),
		UpdatedAt: c.UpdatedAt.Format(time.RFC3339),
	}
	return &conversation, nil
}

// GetDeptByID is the resolver for the GetDeptById field.
func (r *queryResolver) GetDeptByID(ctx context.Context, deptID int32) (*model.DeptByID, error) {
	user, ok := ctx.Value(jwt.MainUserContextKey).(*models.MainUser)
	if !ok {
		return nil, errors.New("Cannot load user from context")
	}

	d, err := r.DeptService.GetDeptById(ctx, deptID, int32(user.ID))
	if err != nil {
		return nil, err
	}

	deptUserList := make([]*model.DeptUser, 0)
	for _, val := range d.DeptUserList {
		du := model.DeptUser{
			ID:       val.ID,
			Fio:      val.FIO,
			Position: &val.Position,
			PhotoURL: val.PhotoURL,
		}
		deptUserList = append(deptUserList, &du)
	}
	return &model.DeptByID{
		ID:           d.ID,
		Name:         d.Name,
		Parent:       d.Parent,
		ParentName:   d.ParentName,
		Head:         d.Head,
		HeadFio:      d.HeadFIO,
		DeptUserList: deptUserList,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
