package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"errors"
	"fmt"
	"konsin1988/rt-app/auth/jwt"
	"konsin1988/rt-app/domain/texx"
	"konsin1988/rt-app/graph/model"
	"konsin1988/rt-app/helpers"
	"strings"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user := ctx.Value(jwt.AuthUserContextKey)
	if user == nil {
		return nil, errors.New("Unauthorized from resolver")
	}

	authUser, ok := user.(*jwt.User)
	if !ok {
		return nil, errors.New("Invalid user in context")
	}

	bitrixUser, err := r.UserService.GetUser(ctx, authUser.Email)
	if err != nil {
		return nil, err
	}

	return &model.User{
		Email:      bitrixUser.Email,
		FirstName:  bitrixUser.FirstName,
		LastName:   bitrixUser.LastName,
		SecondName: bitrixUser.SecondName,
		Wphone:     &bitrixUser.Wphone,
		Phone:      &bitrixUser.Phone,
		Position:   &bitrixUser.Position,
		Birthday:   &bitrixUser.Birthday,
		Dept:       &bitrixUser.Dept,
		Head:       &bitrixUser.Head,
		ImageURL:   &bitrixUser.PhotoURL,
	}, nil
}

// TexxPosts is the resolver for the texxPosts field.
func (r *queryResolver) TexxPosts(ctx context.Context) ([]*model.TexxPost, error) {
	texxPosts, err := texx.FetchTexxPosts()
	if err != nil {
		return nil, err
	}

	var posts []*model.TexxPost
	for _, tex := range texxPosts {
		var bPostText strings.Builder
		for _, ContentPart := range tex.Content {
			if ContentPart.ContentType == "paragraph" {
				var bContentPartText strings.Builder
				for _, ChildrenPart := range ContentPart.ContentChildren {
					if ChildrenPart.ChildrenType == "text" {
						bContentPartText.WriteString(ChildrenPart.ChildrenText)
					} else if ChildrenPart.ChildrenType == "link" {
						bContentPartText.WriteString(ChildrenPart.LinkChildren[0].LinkText)
					}
				}
				ContentPartText := bContentPartText.String()
				bPostText.WriteString(ContentPartText)
				bPostText.WriteString("\n")
			}
		}
		PostText := bPostText.String()
		PostText = strings.Join(strings.Split(PostText, "\n")[:3], "\n\n")
		posts = append(posts, &model.TexxPost{
			DocumentID:   tex.DocumentId,
			Title:        tex.Title,
			Link:         fmt.Sprintf("https://texx.digital/news-and-articles/article/%s", tex.Slug),
			PublishedAt:  helpers.GetRussianDate(tex.PublishedAt),
			PreviewImage: fmt.Sprintf("https://texx.digital%s", tex.PreviewImage.Formats.Small.Url),
			PostText:     PostText,
		})
	}
	return posts, nil
}

// ConversationList is the resolver for the ConversationList field.
func (r *queryResolver) ConversationList(ctx context.Context) ([]*model.ConversationListItem, error) {
	panic(fmt.Errorf("not implemented: ConversationByID - ConversationById"))
}

// ConversationByID is the resolver for the ConversationById field.
func (r *queryResolver) ConversationByID(ctx context.Context) (*model.Conversation, error) {
	panic(fmt.Errorf("not implemented: ConversationByID - ConversationById"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
