scalar Date

type User {
  email: String!
  firstName: String!
  lastName: String!
  secondName: String!
  birthday: String 
  wphone: String
  phone: String
  position: String
  dept: String 
  head: String 
  imageURL: String
}
type UserContact {
  label: String
  type: String!
  value: String!
}
type Query {
  me: User
}

# texx
type TexxPost {
  DocumentId:	ID!	  
  Title:	String!
  Link:		String!
  PublishedAt:	String!
  PreviewImage: String!
  PostText:	String!
}

extend type Query {
  texxPosts: [TexxPost!]!
}

# ai
type Conversation {
  id: ID!
  title: String
  messages(limit: Int, offset: Int): [Message!]!
  createdAt: Date!
  updatedAt: Date!
} 

type ConversationListItem {
  id: ID!
  title: String
}

type Message {
  id: ID!
  role: MessageRole!
  content: String!
  createdAt: Date!
}

enum MessageRole {
  USER
  ASSISTANT
  SYSTEM
}

extend type Query {
  ConversationList: [ConversationListItem!]!
}

extend type Query {
  ConversationById: Conversation!
}




































