package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"errors"
	"konsin1988/rt-app/auth/jwt"
	ghost "konsin1988/rt-app/domain/post"
	"konsin1988/rt-app/graph/model"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user := ctx.Value(jwt.UserContextKey)
	if user == nil {
		return nil, errors.New("Unauthorized from resolver")
	}

	authUser, ok := user.(*jwt.User)
	if !ok {
		return nil, errors.New("Invalid user in context")
	}

	return &model.User{
		Login: authUser.Email,
		Email: authUser.Email,
	}, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	ghostPosts, err := ghost.FetchGhostPosts()
	if err != nil {
		return nil, err
	}

	var posts []*model.Post
	for _, gp := range ghostPosts {
		posts = append(posts, &model.Post{
			ID:	      gp.ID,
			Title:	      gp.Title,
			HTML:	      gp.HTML,
			Slug:	      gp.Slug,
			FeatureImage: gp.FeatureImage,
		})
	}
	return posts, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
