---
name: rt_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  design_system:
    path: ./packages/design_system
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.3.0
  go_router: ^17.0.0
  flutter_svg: ^2.2.2
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  graphql_flutter: ^5.2.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
# For information on the generic Dart part of this file, see the
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/app/
    - assets/images/patern/
    - assets/images/drop/
    - assets/images/bottom_navbar/
