services:
  # ---------------------------
  # Dev 
  # --------------------------
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: konsin1988/rt-go-dev:1.0.0
    container_name: rt-go-dev 
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - /app/tmp
    environment:
      - GO_ENABLED=0
      - GO111MODULE=on
    restart: unless-stopped
    command: air /app
    networks:
      - rt-app

  # -------------------------
  # Prod
  # --------------------------
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: konsin1988/rt-go:1.0.0
    container_name: rt-go
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - rt-app
  
  # ---------------------------
  # Worker dev 
  # --------------------------
  worker-dev:
    build:
      context: .
      dockerfile: Dockerfile.worker.dev
    container_name: rt-app-worker-dev 
    env_file: .env
    volumes:
      - ./worker:/worker
      - /worker/tmp
    environment:
      - GO111MODULE=on
    restart: unless-stopped
    command: air /worker
    networks:
      - rt-app

networks:
  rt-app:
    name: rt-app
    external: True
