FROM golang:1.25-alpine

WORKDIR /worker

RUN apk add --no-cache git curl && \ 
	go install github.com/air-verse/air@v1.64.5

COPY ./worker/go.mod /worker/ 
RUN go mod download

COPY ./worker .

CMD ["air", "/worker"]

