services:
  # ---------------------------
  # Dev 
  # --------------------------
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ${PROJECT_NAME}-api-dev
    image: konsin1988/${PROJECT_NAME}-api-dev:${PROJECT_VERSION}
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - /app/tmp
    environment:
      - GO_ENABLED=0
      - GO111MODULE=on
    restart: unless-stopped
    mem_limit: 1G
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    logging:
      driver: json-file
      options:
        max-size: "10M"
        max-file: "3" 
    command: air /app
    networks:
      - rt-app

  # -------------------------
  # Prod
  # --------------------------
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: konsin1988/rt-go:1.0.0
    container_name: rt-go
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    mem_limit: 1G
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    logging:
      driver: json-file
      options:
        max-size: "10M"
        max-file: "3" 
    networks:
      - rt-app
  
  # ---------------------------
  # Worker dev 
  # --------------------------
  worker-dev:
    build:
      context: .
      dockerfile: Dockerfile.worker.dev
    container_name: ${PROJECT_NAME}-worker-dev
    image: konsin1988/${PROJECT_NAME}-worker-dev:${PROJECT_VERSION}
    env_file: .env
    volumes:
      - ./worker:/worker
      - /worker/tmp
    environment:
      - GO111MODULE=on
    restart: unless-stopped
    command: air /worker
    mem_limit: 1G
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    logging:
      driver: json-file
      options:
        max-size: "10M"
        max-file: "3" 
    networks:
      - rt-app

networks:
  rt-app:
    name: rt-app
    external: True
