// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type User struct {
	Login          string  `json:"login"`
	About          *string `json:"about,omitempty"`
	AvatarImageURL *string `json:"avatarImageUrl,omitempty"`
	DisplayName    *string `json:"displayName,omitempty"`
	Email          string  `json:"email"`
}

type UserContact struct {
	Label *string `json:"label,omitempty"`
	Type  string  `json:"type"`
	Value string  `json:"value"`
}
