// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Conversation struct {
	ID        int32      `json:"id"`
	Title     *string    `json:"title,omitempty"`
	Messages  []*Message `json:"messages"`
	CreatedAt string     `json:"createdAt"`
	UpdatedAt string     `json:"updatedAt"`
}

type ConversationListItem struct {
	ID        int32  `json:"id"`
	Title     string `json:"title"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Department struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	Parent int32  `json:"parent"`
	Head   int32  `json:"head"`
}

type DeptByID struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	Parent       *int32      `json:"parent,omitempty"`
	ParentName   *string     `json:"parentName,omitempty"`
	Head         *int32      `json:"head,omitempty"`
	HeadFio      *string     `json:"headFIO,omitempty"`
	DeptUserList []*DeptUser `json:"deptUserList"`
}

type DeptUser struct {
	ID       int32   `json:"id"`
	Fio      string  `json:"fio"`
	Position *string `json:"position,omitempty"`
	PhotoURL *string `json:"photoURL,omitempty"`
}

type Head struct {
	ID  int32  `json:"id"`
	Fio string `json:"fio"`
}

type Message struct {
	ID        int32       `json:"id"`
	Role      MessageRole `json:"role"`
	Content   string      `json:"content"`
	CreatedAt string      `json:"createdAt"`
}

type Query struct {
}

type TexxPost struct {
	DocumentID   string `json:"DocumentId"`
	Title        string `json:"Title"`
	Link         string `json:"Link"`
	PublishedAt  string `json:"PublishedAt"`
	PreviewImage string `json:"PreviewImage"`
	PostText     string `json:"PostText"`
}

type User struct {
	ID         int32         `json:"id"`
	FirstName  string        `json:"firstName"`
	LastName   string        `json:"lastName"`
	SecondName *string       `json:"secondName,omitempty"`
	Email      string        `json:"email"`
	Birthday   *string       `json:"birthday,omitempty"`
	PhotoURL   *string       `json:"photoURL,omitempty"`
	Mobile     *string       `json:"mobile,omitempty"`
	Inner      *string       `json:"inner,omitempty"`
	Position   *string       `json:"position,omitempty"`
	DeptList   []*Department `json:"deptList"`
	HeadList   []*Head       `json:"headList"`
}

type UserContact struct {
	Label *string `json:"label,omitempty"`
	Type  string  `json:"type"`
	Value string  `json:"value"`
}

type MessageRole string

const (
	MessageRoleUser      MessageRole = "USER"
	MessageRoleAssistant MessageRole = "ASSISTANT"
	MessageRoleSystem    MessageRole = "SYSTEM"
)

var AllMessageRole = []MessageRole{
	MessageRoleUser,
	MessageRoleAssistant,
	MessageRoleSystem,
}

func (e MessageRole) IsValid() bool {
	switch e {
	case MessageRoleUser, MessageRoleAssistant, MessageRoleSystem:
		return true
	}
	return false
}

func (e MessageRole) String() string {
	return string(e)
}

func (e *MessageRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MessageRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MessageRole", str)
	}
	return nil
}

func (e MessageRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MessageRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MessageRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
