// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type TexxPost struct {
	DocumentID   string `json:"DocumentId"`
	Title        string `json:"Title"`
	Link         string `json:"Link"`
	PublishedAt  string `json:"PublishedAt"`
	PreviewImage string `json:"PreviewImage"`
	PostText     string `json:"PostText"`
}

type User struct {
	Email      string  `json:"email"`
	FirstName  string  `json:"firstName"`
	LastName   string  `json:"lastName"`
	SecondName string  `json:"secondName"`
	Birthday   *string `json:"birthday,omitempty"`
	Wphone     *string `json:"wphone,omitempty"`
	Phone      *string `json:"phone,omitempty"`
	Dept       *string `json:"dept,omitempty"`
	Head       *string `json:"head,omitempty"`
	ImageURL   *string `json:"imageURL,omitempty"`
}

type UserContact struct {
	Label *string `json:"label,omitempty"`
	Type  string  `json:"type"`
	Value string  `json:"value"`
}
